version: '3'

services:
  struts:
    container_name: struts
    image: pancontent/s2-009_struts2
    ports:
      - 80:8080
    volumes:
      - splunk-logs:/splunk/access-logs
      - ./struts-actionchaining.xml:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/struts-actionchaining.xml
      - ./logging.properties:/usr/local/tomcat/conf/logging.properties
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    links:
      - splunkenterprise

 
      
  splunkenterprise:
    container_name: splunkenterprise
    hostname: splunkenterprise
    image: splunk/splunk
    user: root
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_PASSWORD: changemelad
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
      - splunk-logs:/tomcat-container:rw
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"



volumes:
  opt-splunk-etc:
  opt-splunk-var:
  splunk-logs:
